/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2023-09-02 21:48:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.restaurant.domain.MenuItem;
import com.restaurant.domain.MenuCategory;

public final class searchResults_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.restaurant.domain.MenuItem");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.restaurant.domain.MenuCategory");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<title>Search Results</title>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Raleway\">\n");
      out.write("<style>\n");
      out.write("body, h1, h5 {\n");
      out.write("\tfont-family: \"Raleway\", sans-serif\n");
      out.write("}\n");
      out.write("\n");
      out.write("body, html {\n");
      out.write("\theight: 100%\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bgimg {\n");
      out.write("\tbackground-image: url('blog-img.jpg');\n");
      out.write("\tbackground-repeat: no-repeat;\n");
      out.write("\tmin-height: 100%;\n");
      out.write("\tbackground-position: center;\n");
      out.write("\tbackground-size: cover;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div class=\"bgimg w3-display-container w3-text-black\">\n");
      out.write("\t\t<div class=\"w3-display-topleft w3-jumbo\">\n");
      out.write("\t\t\t<p>Welcome to Harsh's Cafe</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"w3-display-middle w3-container w3-xxxlarge\">\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<button\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('menu').style.display='block'\"\n");
      out.write("\t\t\t\t\tclass=\"w3-button w3-black\">Menu</button>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"w3-display-bottomright w3-container w3-xlarge\">\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<button\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('contact').style.display='block'\"\n");
      out.write("\t\t\t\t\tclass=\"w3-button w3-black\">Contact</button>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"w3-display-bottomleft w3-container\">\n");
      out.write("\t\t\t<p class=\"w3-xlarge\">Monday - Friday 8am - 6pm | Weekends 9am -\n");
      out.write("\t\t\t\t5pm</p>\n");
      out.write("\t\t\t<p class=\"w3-large\">42 Village St, Fremont, California - 94539</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\tpowered by <a href=\"https://www.w3schools.com/w3css/default.asp\"\n");
      out.write("\t\t\t\t\ttarget=\"_blank\">w3.css</a>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Menu Modal -->\n");
      out.write("\t<div id=\"menu\" class=\"w3-modal\">\n");
      out.write("\t\t<div class=\"w3-modal-content w3-animate-zoom\">\n");
      out.write("\t\t\t<div class=\"w3-container w3-black w3-display-container\">\n");
      out.write("\t\t\t\t<span onclick=\"document.getElementById('menu').style.display='none'\"\n");
      out.write("\t\t\t\t\tclass=\"w3-button w3-display-topright w3-large\">x</span>\n");
      out.write("\t\t\t\t");

				List<MenuItem> menuItems = (List<MenuItem>) request.getAttribute("menuItems");
				for (MenuCategory category : MenuCategory.values()) {
				
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"w3-container w3-black \">\n");
      out.write("\t\t\t\t<h1>");
      out.print(category);
      out.write("</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"w3-container\">\n");
      out.write("\t\t\t\t");

				for (MenuItem menuItem : menuItems) {
					if (menuItem.getCategory().toString().equals(category.toString())) {
						out.println("<h5>" + menuItem.getName() + " $" + "<b>" + menuItem.getPrice() + "</b></h5>");
					}
				}
				}
				
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Contact Modal -->\n");
      out.write("\t<div id=\"contact\" class=\"w3-modal\">\n");
      out.write("\t\t<div class=\"w3-modal-content w3-animate-zoom\">\n");
      out.write("\t\t\t<div class=\"w3-container w3-black\">\n");
      out.write("\t\t\t\t<span\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('contact').style.display='none'\"\n");
      out.write("\t\t\t\t\tclass=\"w3-button w3-display-topright w3-large\">x</span>\n");
      out.write("\t\t\t\t<h1>Contact</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"w3-container\">\n");
      out.write("\t\t\t\t<p>Reserve a table, ask for today's special or just send us a\n");
      out.write("\t\t\t\t\tmessage:</p>\n");
      out.write("\t\t\t\t<form action=\"/action_page.php\" target=\"_blank\">\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input w3-padding-16 w3-border\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Name\" required name=\"Name\">\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input w3-padding-16 w3-border\" type=\"number\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"How many people\" required name=\"People\">\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input w3-padding-16 w3-border\"\n");
      out.write("\t\t\t\t\t\t\ttype=\"datetime-local\" placeholder=\"Date and time\" required\n");
      out.write("\t\t\t\t\t\t\tname=\"date\" value=\"2020-11-16T20:00\">\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input w3-padding-16 w3-border\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Message \\ Special requirements\" required\n");
      out.write("\t\t\t\t\t\t\tname=\"Message\">\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t<button class=\"w3-button\" type=\"submit\">SEND MESSAGE</button>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
